### PR TITLE
Add debianisation for version 3.1.2 [REVPI-3238]

### PR DESCRIPTION
**Pull request by tboehler1**
The tag for v3.1.2 is necessary on master. For this, commit 81bccba98674bf94760f275de4f764403b134821 is used. This tag will be pushed when this PR is merged but exists on my fork already.

### CODE REVIEW

**Review by naruxde — APPROVED** [review]

**Review by RamiGspo — APPROVED** [review]

**Comment by tboehler1** [comment]
The next step is testing the bullseye package and putting it on our package repo. Can one of the participants do some testing for this, too, so we can release it?

**Comment by nbuchwitz** [comment]
Successfully tested on Connect 4 and KUNBUS Flat (with CM3+). Login time looks reasonable on Flat:
```
default.target @779ms
└─basic.target @772ms
  └─sockets.target @772ms
    └─dbus.socket @738ms +34ms
      └─app.slice @733ms
        └─-.slice @686ms
pi@RevPi465:~ $ 
```

**Review by nbuchwitz — COMMENTED** [review]
LGTM

**Comment by tboehler1** [comment]
@nbuchwitz Thanks!

@naruxde All the necessary files should be uploaded to the usual place. Feel free to move them to our package repository.

**Pull request merged**
